version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: '7999'
    ports:
      - '7999:7999'
    image: avag-sargsyan/word-of-wisdom-pow/server:latest
    restart: 'no'
    
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: '7999'
    image: avag-sargsyan/word-of-wisdom-pow/client:latest
    restart: 'no'
    depends_on:
      - server
